=== croqueGrec09/KeletiPu/analysyscities/dialogData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    This is the schema for a dialog document. Each city has a such one. It is divided 
    into different NPCs (non player characters) where an NPC element may mean several 
    actual participants. To each point, a set of possible responses is connected from 
    which the player may pick one. They may be conditioned or randomised.
    
    author: András Gálffy, andrisgalffy@gmail.com, matricula number #5584124
    current version: 0.701 from July 7th, 2018
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:include schemaLocation="town.xsd"/>
    <xs:include schemaLocation="../item.xsd"/>
    <xs:element name="dialogueData" type="dialogueData">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                The dialog root.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="dialogueData">
        <xs:sequence>
            <xs:element name="person" type="person" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The different NPCs that may occur in a town.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="person">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Definition of an NPC (non playing character). A person may mean several 
                actual people who respond as group before the player may take an action.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="stream" type="stream" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The different streams of speech turns.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    Each person has an identifier to be addressable.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <!-- definition of a stream of speech turns -->
    <xs:complexType name="stream">
        <xs:sequence>
            <xs:element name="point" type="point" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        A point, consisting of action and reaction
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    Each stream has an identifier to be addressable.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <!-- a point of answer and reaction -->
    <xs:complexType name="point">
        <xs:sequence>
            <xs:element name="answer" type="dialogText"/>
            <xs:element name="conditionedAction" type="conditionedAction" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="action" type="dialogAction" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="pointGrp" type="xs:string"/>
        <xs:attribute name="disable" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="dialogAction">
        <xs:sequence>
            <xs:element name="response" type="dialogText"/>
            <xs:element name="command" type="command"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="conditionedAction">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="if" type="condAnswer" maxOccurs="unbounded"/>
            <xs:element name="else-if" type="condAnswer" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="else" type="dialogAction" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="condAnswer">
        <xs:complexContent>
            <xs:extension base="dialogAction">
                <xs:attribute name="conditionToTest" type="xs:string" use="required"/>
                <xs:attribute name="requirement" type="xs:string" use="required"/>
                <xs:attribute name="evaluation" type="xs:boolean" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="command">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="dialog" type="nextDialog"/>
            <xs:element name="dialogChoice" type="dialogChoice"/>
            <xs:element name="getItem" type="itemManipulation"/>
            <xs:element name="giveItem" type="itemManipulation"/>
            <xs:element name="getMoney" type="moneyManipulation"/>
            <xs:element name="giveMoney" type="moneyManipulation"/>
            <xs:element name="event" type="event"/>
            <xs:element name="exit">
                <xs:complexType/>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="nextDialog">
        <xs:attribute name="point" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="dialogChoice">
        <xs:attribute name="pointGrp" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="event">
        <xs:attribute name="base" type="xs:string" use="required"/>
        <xs:attribute name="stream" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="itemManipulation">
        <xs:attribute name="triggeredItem" type="xs:string" use="required"/>
        <xs:attribute name="eliminateAction" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="moneyManipulation">
        <xs:attribute name="amount" type="xs:int"/>
    </xs:complexType>
    <xs:complexType name="dialogText">
        <xs:sequence>
            <xs:element name="de" type="textElement" minOccurs="0"/>
            <xs:element name="hu" type="textElement" minOccurs="0"/>
            <xs:element name="fr" type="textElement" minOccurs="0"/>
            <xs:element name="en" type="textElement" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:complexType name="textElement" mixed="true">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="userName" />
            <xs:element name="currentMoney" />
            <xs:element name="loveInterest" type="randomisedUserEnumeration" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="randomisedUserEnumeration">
        <xs:attribute name="n" type="nControlledValue" default="randomNumber"/>
    </xs:complexType>
    <xs:simpleType name="nControlledValue">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d|randomNumber"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== croqueGrec09/KeletiPu/analysyscities/zeidel_dialog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    This is the dialog repository for Zeidel city. 
    For the structure and possibilities, see the associated XSD schema.
-->
<dialogueData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dialogData.xsd">
    <!-- the assistant at the light railway counter -->
    <person id="HbfMitteUndergroundCounterAssistant">
        <stream id="0">
            <point id="0">
                <answer id="HbfMitteUndergroundCounterAssistant00">
                    <de> "Guten Tag! Sie sehen etwas verloren aus! Wie kann ich Ihnen weiterhelfen?" </de>
                    <fr>« Bonjour ! Vous avez l'air un peu perdu ! Comment puis-je vous aider ?
                        »</fr>
                <en>"Good afternoon! You look a bit lost! How can I help you?"</en></answer>
                <action>
                    <response id="HbfMitteUndergroundCounterAssistant000">
                        <de>"Nein, es ist alles in Ordnung, danke!"</de>
                        <fr>« Non, ça va, merci ! »</fr>
                    <en>"No, everything alright, thank you!"</en></response>
                    <command>
                        <exit/>
                    </command>
                </action>
                <action>
                    <response id="HbfMitteUndergroundCounterAssistant001">
                        <de>"Oh, sieht man das? In der Tat, ich möchte zur Station Télégraphe."</de>
                    <fr>« Oh, ça se voit ? En effet, je voudrais aller à la station Télégraphe. »</fr><en>"Oh, you can see that? Indeed, I would like to go to the Télégraphe underground station."</en></response>
                    <command>
                        <dialog point="1"/>
                    </command>
                </action>
            </point>
            <point id="1">
                <answer id="HbfMitteUndergroundCounterAssistant01">
                    <de> "Alles klar! Gehen Sie zur Metrolinie 7 auf Gleis 39. Fahren Sie dort zwei
                        Haltestellen Richtung Chargy." </de>
                <fr>« Bien sûr ! Allez à la ligne 7 vers Chargy sur voie 39. Descendez aprés deux stations. »</fr><en>"Alright! Go to the underground line 7 on platform 39. Go two stations towards Chargy."</en></answer>
                <action>
                    <response id="HbfMitteUndergroundCounterAssistant010">
                        <de>"Vielen lieben Dank! Auf Wiedersehen!"</de>
                    <fr>« Merci beaucoup ! Au revoir ! »</fr><en>"Thank you very much! Bye!"</en></response>
                    <command>
                        <exit/>
                    </command>
                </action>
            </point>
        </stream>
    </person>
    <!-- the vendor at the travellers centre -->
    <person id="ZVWvendor">
        <stream id="0">
            <point id="0">
                <answer id="ZVWvendor00">
                    <de> "Herzlich willkommen bei den Zeidel'schen Verkehrswerken! Wie kann ich
                        Ihnen helfen?" </de>
                <fr>« Bienvenue aux compagnies des transports Zeideliens ! Comment pourrais-je vous être utile ? »</fr><en>"Welcome at the Zeidelian transport company! How may I help you?"</en></answer>
                <action>
                    <response id="ZVWvendor000">
                        <de>"Ich möchte bitte eine Fahrkarte kaufen!"</de>
                    <fr>« Je voudrais m'acheter un billet. »</fr><en>"I would like to buy a ticket!"</en></response>
                    <command>
                        <dialog point="1"/>
                    </command>
                </action>
                <action>
                    <response id="ZVWvendor001">
                        <de>"Gar nicht, ich wollte mich nur umsehen - entschuldigen Sie bitte!"</de>
                    <fr>« Pas du tout, je voulais juste regarder, merci ! »</fr><en>"Not at all, I am just looking - excuse me please!"</en></response>
                    <command>
                        <exit/>
                    </command>
                </action>
            </point>
            <point id="1">
                <answer id="ZVWvendor01">
                    <de>"Sehr gerne! Wo soll es denn hingehen?"</de>
                <fr>« Avec plaisir ! Où est-ce que vous aimeriez partir ? »</fr><en>"With pleasure! Where would you like to go?"</en></answer>
                <conditionedAction>
                    <if conditionToTest="checkItem" requirement="ticketToKvirasim" evaluation="false">
                        <response id="ZVWvendor010">
                            <de>"Nach Kvirasim."</de>
                        <fr>« À Kvirasim. »</fr><en>"To Kvirasim."</en></response>
                        <command>
                            <dialog point="37"/>
                        </command>
                    </if>
                </conditionedAction>
                <!-- TODO #203 multiple conditioned elements do not display -->
                <conditionedAction>
                    <if conditionToTest="checkItem" requirement="ticketToKarlstadt" evaluation="false">
                        <response id="ZVWvendor011">
                            <de>"Nach Karlstadt."</de>
                        <fr>« À Karlstadt. »</fr><en>"To Karlstadt."</en></response>
                        <command>
                            <dialog point="310b"/>
                        </command>
                    </if>
                </conditionedAction>
                <action>
                    <response id="ZVWvendor012">
                        <de>"Ja ... ich weiß noch nicht so recht ... können Sie vielleicht etwas
                            empfehlen?"</de>
                    <fr>« Ben... je ne sais pas encore... pourriez-vous me conseiller quelque chose ? »</fr><en>"Yes ... I do not really know ... can you suggest me something?"</en></response>
                    <command>
                        <dialogChoice pointGrp="2"/>
                    </command>
                </action>
                <action>
                    <response id="ZVWvendor013">
                        <de>"Entschuldigen Sie, ich möchte doch nicht reisen! Auf Wiedersehen!"</de>
                    <fr>« Excusez-moi... je ne veux plus voyager ! Au revoir ! »</fr><en>"Excuse me, I do not would like to travel! Good bye!"</en></response>
                    <command>
                        <exit/>
                    </command>
                </action>
            </point>
            <point pointGrp="2" id="20">
                <answer id="ZVWvendor020">
                    <de>"Hm ... wird schwierig. Vielleicht schauen Sie sich einwenig die Züge an und
                        kommen später?"</de>
                <fr>« Hm... ce sera difficile. Peut-être vous regardez un peu les trains et revenez plus tard ? »</fr><en>"Hm ... difficult. Maybe you take a look at the trains and come later?"</en></answer>
                <action>
                    <response id="ZVWvendor0201">
                        <de>"Ja, das werde ich! Danke sehr!"</de>
                    <fr>« Oui, je ferai ! Merci beaucoup ! »</fr><en>"Yes, I shall do so! Thank you very much!"</en></response>
                    <command>
                        <exit/>
                    </command>
                </action>
            </point>
            <!-- stream Kvirasim - analysis city 7 -->
            <point disable="self,47" pointGrp="2" id="27">
                <answer id="ZVWvendor027">
                    <de>"Alles klar ... Hier! Seit neuestem wieder erreichbar: Die Stadt Kvirasim.
                        Das ist zwar recht weit weg, aber Sie würden dann den ganzen Planeten
                        durchreisen. Im Südosten der Einöde, schöne phonetische Landschaft, dort hat
                        man sich den Tönen gewidmet. Wäre das nicht etwas für Sie?"</de>
                <fr>« D'accord... voilà ! Desservi depuis le plus récent : la ville de Kvirasim. C'est assez loin, mais vous traverseriez toute la planète. Dans le sud-est du désert, beau paysage phonétique, on s'est consacré aux sons. Ceci ne serait pas quelque chose pour vous ? »</fr><en>"Alright ... here! Very recently opened: the city of Kvirasim. That is quite far away, but you would travel through the whole planet. In the south east of the wasteland, beautiful phonetic landscape, they consacred themselves to the sounds. Would that not be something for you?"</en></answer>
                <conditionedAction>
                    <if conditionToTest="checkItem" requirement="ticketToKvirasim" evaluation="false">
                        <response id="ZVWvendor0270">
                            <de>"Nach Kvirasim! Die Laute, die Vokale, super. Da will ich hin!"</de>
                        <fr>« À Kvirasim ! Les sons, les voyelles, super. C'est là où je veux y aller ! »</fr><en>"To Kvirasim! The sounds, the vocals, awesome. I would like to go there!"</en></response>
                        <command>
                            <dialog point="37"/>
                        </command>
                    </if>
                </conditionedAction>
                <action>
                    <response id="ZVWvendor0271">
                        <de>"Hm, das ist echt sehr interessant, aber haben Sie nicht noch etwas
                            anderes?"</de>
                    <fr>« Hm, c'est fort intéressant, mais est-ce que vous n'avez pas d'autre chose ? »</fr><en>"Hm, that is surely interesting, but do you not have anything else?"</en></response>
                    <command>
                        <dialogChoice pointGrp="2"/>
                    </command>
                </action>
                <action>
                    <response id="ZVWvendor0272">
                        <de>"Ähm ... Ich schaue mich doch lieber um. Vielen Dank!"</de>
