=== croqueGrec09/KeletiPu/analysyscities/happening.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    This is the schema for a happening repository. A happening is a stream of points the 
    player may click through. Trips with public transports are also defined as a stream of 
    happenings where each station represents a point. At each point, a video or a still 
    image may be shown.
    Each point may trigger a chain of other events.
    
    author: András Gálffy, andrisgalffy@gmail.com, matricula number #5584124
    current version: 0.701 from July 7th, 2018
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
    <xs:include schemaLocation="town.xsd"/>
    <xs:element name="happening">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="stream" type="stream" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="idPrefix" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="stream">
        <xs:sequence>
            <xs:element name="event" type="event" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="event" mixed="true">
        <xs:sequence>
            <xs:choice>
                <xs:element name="eventBody" type="page" />
                <xs:element name="eventMultimedia" type="multimediaPage" />
            </xs:choice>
            <xs:element name="nextEvent" type="streamPoint" minOccurs="0"/>
            <xs:element name="previousEvent" type="streamPoint" minOccurs="0"/>
            <xs:element name="exitStream" type="newPlace" minOccurs="0"/>
            <xs:element name="otherHappenings" type="command" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:complexType name="page">
        <xs:sequence>
            <xs:element name="image" type="image" maxOccurs="4"/>
            <xs:element name="text" type="text"/>
            <xs:element name="sound" type="sound" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="multilingual" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType name="multimediaPage">
        <xs:sequence>
            <xs:element name="baseFile" type="videoFileName" />
            <xs:element name="setImages" type="assocList"/>
            <xs:element name="imgInterval" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="assocList">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="assocData" type="assoc"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="assoc">
        <xs:attribute name="dataType" type="dataTypeRestriction" use="required"/>
        <xs:attribute name="filePath" type="fileTypeRestriction" use="required"/>
    </xs:complexType>
    <xs:simpleType name="dataTypeRestriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="image"/>
            <xs:enumeration value="sound"/>
            <xs:enumeration value="video"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="fileTypeRestriction">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*\.(mp4|mp3|jpg|png)"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="streamPoint">
        <xs:attribute name="pointRef" type="xs:IDREF" use="required"/>
    </xs:complexType>
    <xs:complexType name="newPlace">
        <xs:sequence>
            <xs:element name="nextCity" type="xs:string"/>
            <xs:element name="nextStation" type="xs:int"/>
            <xs:element name="nextPlace" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="command">
        <xs:sequence>
            <xs:element name="addItem" type="itemManipulation" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="removeItem" type="itemManipulation" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="addMoney" type="moneyManipulation" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="deductMoney" type="moneyManipulation" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="addQuest" type="questManipulation" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="updateQuest" type="updateQuest" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="completeQuest" type="completeQuest" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="itemManipulation">
        <xs:attribute name="itemID" type="xs:NCName" use="required"/>
        <xs:attribute name="valid" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true"/>
                    <xs:enumeration value="false"/>
                    <xs:enumeration value="none"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="moneyManipulation">
        <xs:attribute name="amount" type="xs:int" use="required"/>
    </xs:complexType>
</xs:schema>

=== croqueGrec09/KeletiPu/analysyscities/kvirasim_kvb.000.xml
<?xml version="1.0" encoding="UTF-8"?>
<happening xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="happening.xsd" idPrefix="kv">
    <stream id="u11" name="Stadtbahnlinie 11">
        <event id="u1101">
            <eventBody>
                <image lang="all">kvirasim/events/u11_01.jpg</image>
                <text lang="de">
                    Der Stadtführer begrüßt die Fahrgäste, die interessiert die neue Stadtbahn betrachten: 
                    "Herzlich willkommen in der Stadtbahn! Wir sind glücklich, Ihnen diesen kleinen Abschnitt 
                    zeigen zu dürfen - bereiten Sie sich auf eine spannende Fahrt vor und abonnieren Sie fleißig! 
                    Denn dann haben Sie bei der Eröffnung die Möglichkeit auf eine Freifahrt durch das gesamte 
                    Verbundgebiet!"!NL
                    Er holt danach Luft und erklärt:
                    "Der nächste Halt ist die Erzeugung von Sprache. Lassen Sie sich hier die aerodynamisch-myoelastische 
                    Theorie der Spracherzeugung anhand unseres Modells erklären - das Haus der Vokale und das Haus der 
                    Konsonanten eröffnen demnächst und stellen ihr interaktives Lungenmodell dar!"
                </text>
            </eventBody>
            <nextEvent pointRef="u1102"/>
        </event>
        <event id="u1102">
            <eventBody>
                <image lang="all">kvirasim/events/u11_02.jpg</image>
                <text lang="de">
                    "Der nun folgende Halt ist die Schallformstraße. Auf diesem Bild sehen Sie die unterschiedlichen Formen 
                    von Schall - ganz vorn den quasi-periodischen Schall, danach ein Friktionsrauschen und nach erneutem 
                    quasi-periodischem Schall die Stille. Quasi-periodisch, weil die menschliche Stimme keine klaren Sinustöne 
                    erzeugt, sondern Obertöne im Schall enthalten sind - mehr dazu an den folgenden Haltestellen."
                </text>
            </eventBody>
            <nextEvent pointRef="u1103"/>
        </event>
        <event id="u1103">
            <eventBody>
                <image lang="all">kvirasim/events/u11_03.jpg</image>
                <text lang="de">
                    "Ein wenig überdimensioniert ist dieses Bild von der Frequenzstraße. Schall verbreitet sich, indem 
                    sich ein bestimmtes Medium verdünnt und verdichtet - in der Luft zum Beispiel löst der Druck unseres 
                    Zwerchfelles eine Bewegung der Luftmoleküle aus. Diese bewegen sich in einem bestimmten Zeitabstand 
                    gewisse Male hin und her - und diese Bewegung -Luftverdichtung bzw. -verdünnung- können wir hören. 
                    Und wie oft in einer Sekunde sich diese Bewegung wiederholt, das gibt die Frequenz an."
                </text>
            </eventBody>
            <nextEvent pointRef="u1104"/>
        </event>
        <event id="u1104">
            <eventBody>
                <image lang="all">kvirasim/events/u11_04.jpg</image>
                <text lang="de">
                    "Die nächste kurz gestreifte Haltestelle ist der Diagrammenplatz. In der Phonetik werden Messungen 
                    unterschiedlichster Art durchgeführt und die Sprache, die wir aufzeichnen, lässt sich auf unterschiedliche 
                    Art und Weise abbilden. Hier sehen wir zwei Arten von Diagrammen: oben ein Oszillogramm, unten ein Spektragramm. 
                    Für den nächsten Halt wird das letztere von Bedeutung sein."
                </text>
            </eventBody>
            <nextEvent pointRef="u1105"/>
        </event>
        <event id="u1105">
            <eventBody>
                <image lang="all">kvirasim/events/u11_05.jpg</image>
                <text lang="de">
                    "Hier kommen wir zum Formantenweg. Wie ich an der Haltestelle Schallformstraße sagte, setzt sich 
                    der Schall der menschlichen Sprache aus verschiedenen Obertönen zusammen, die sich über dem F0 - 
                    dem Grundton - lagern. Anhand der Formanten F1 und F2 - von unten die zweite und dritte rot 
                    gepunktete Linie - können wir wahrnehmen, welcher Laut gesprochen wurde, denn sie formen sich durch 
                    unsere Artikulatoren: der Zungenposition und dem Öffnungsgrad."
                </text>
            </eventBody>
            <nextEvent pointRef="u1106"/>
        </event>
        <event id="u1106">
            <eventBody>
                <image lang="all">kvirasim/events/u11_06.jpg</image>
                <text lang="de">
                    "Der letzte Halt unseres Demos ist der Platz der Artikulation. Hier lernen Sie in naher Zukunft 
                    über die verschiedenen Wege, die Vorgänge der Artikulation aufzuzeichnen - hier sehen Sie 
                    ein Artikulogramm. Auf den fünf Spuren sind unsere Artikulatoren aufgezeichnet: Lippen, 
                    Zungenspitze, Zungenkörper, Velum und Stimmritze. Jedem Laut wird ein Bewegungsmuster dieser 
                    Artikulatoren zugeordnet und hier sehen Sie, welche Abläufe sich bei der Aussprache des Wortes 
                    "bitte" abspielen.!NL
                    Leider war es das, aus Zeitgründen sind wir mit dem Bau nicht fertig geworden. Aber freuen Sie sich: 
                    in der nächsten Version werden Sie viel besser verstehen und nachempfinden können, was die Stadt 
                    zu bieten hat!"
                </text>
            </eventBody>
            <exitStream>
                <nextCity>kvirasim</nextCity>
                <nextStation>1</nextStation>
                <nextPlace>hbf_underground_platform1a</nextPlace>
            </exitStream>
        </event>
    </stream>
</happening>

=== croqueGrec09/KeletiPu/analysyscities/zvw_intervilles.xml
<?xml version="1.0" encoding="UTF-8"?>
<happening xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="happening.xsd" idPrefix="iv">
    <stream id="Dh2011" name="Schnellzug Zeidel-Cité d'Orcive-Kvirasim">
        <event id="ZDKV01">
            <eventBody>
                <image lang="all">kvirasim/events/ZDKV01.jpg</image>
                <text>
               <de>
                    Du besteigst den Liegewagen nach Kvirasim und schläfst sofort nach Bezug deiner Kabine ein. Es ist 
                    viel mehr passiert, als an so manchen Tagen in deinem studentischen Leben. Die neue Welt, die 
                    eigentlich keine neue Welt ist, sie sieht ja so aus, wie die Erde, aber irgendwie doch ganz anders ...
                    Mit diesem Gefühl wachst du auf, als es in Cité d'Orcive plötzlich heißt: "Alle aussteigen!" Wie gut, 
                    dass du dem Schaffner zugehört hast, als er dir sagte, dass du in den Internight 045 umsteigen musst ...
                    Du schaust dich etwas in der Stadt um, kannst den Bahnhof aber nicht verlassen - denn auch hier befindet 
                    sich eine Analysestadt im Bau.
                </de>
            <fr>Tu montes la voiture couchette vers Kvirasim et endors tout de suite après avoir pris ta cabine. Beaucoup plus s'est passé comme à des autres jours dans ta vie d'étudiante. Ce nouveau monde qui n'en est pas franchement, il a l'air de la Terre, mais est complètement autre... Tu te reveilles avec ce sentiment quand à Cité d'Orcive, on crie : « Tout le monde descend ! » Bien que tu as écouté à l'agent raccompagnant quand il t'a dit(e) qu'il te faut changer dans l'Intercités de nuit 045... Tu regardes un peu dans la ville mais ne peux pas quitter la gare - parce que ici aussi, on construit une ville d'analyse.</fr><en>You board the couchette coach to Kvirasim and fall asleep right after having taken your compartment. So much more things happened like on other days in your student life. The new world which is actually no new world looks like Earth but is something completely else ... you wake up with exactly that felling in Cité d'Orcive when suddenly, someone shouts: "Everyone get off!" How well you did when you paid attention to the conductor when he said to you that you have to change to the Internight 045 ... you look a bit around in the town but cannot leave the station – as here too, an analysis city is under construction.</en></text>
            </eventBody>
            <nextEvent pointRef="ZDKV02"/>
        </event>
        <event id="ZDKV02">
            <eventBody>
                <image lang="all">kvirasim/events/ZDKV02.jpg</image>
                <text>
               <de>
                    Nach einer endlos langen Wartezeit besteigst du den Liegewagen im Internight 045 nach Kvirasim. Und 
                    nach mehrtägiger Fahrt kommst du in der Stadt der Phonetik und der Phonologie an. Diese Stadt hat sich 
                    dem Studienkomplex Phonetik + Phonologie gewidmet und die Fächer sind versorgt, die in diesem Studienmodul 
                    angeboten werden. Besteige die Linie U11, um zu sehen, was dich dort erwartet.
                </de>
            <fr>Après un temps semblablement infini, tu montes la voiture couchettes dans l'Intercités de nuit 045 à Kvirasim. Et après un voyage de plusieurs jours, tu arrives dans la ville de la phonétique et de la phonologie. Cette ville s'est consacrée au complex d'études phonétique + phonologie et ces matières sont servies qu'on offre dans ce module d'études. Monte la ligne U11 pour voir ce qui t'y attend.</fr><en>After a seemingly endless waiting time, you board the couchette coach of the Internight 045 to Kvirasim. And after a journey of several days, you arrive in the city of phonetics and phonology. This city consecrated itself to the phonetics and phonology study complex and those subjects are served which are offered in that study module. Board line U11 to see what awaits you there.</en></text>
            </eventBody>
            <exitStream>
                <nextCity>kvirasim</nextCity>
                <nextStation>1</nextStation>
                <nextPlace>hbf_platform6_7a</nextPlace>
            </exitStream>
        </event>
    </stream>
    <stream id="Dh153" name="Schnellzug Darborough-Karlstadt">
        <event id="ZDKA00">
            <eventMultimedia>
                <baseFile>voyage/voyage_Dh153_Bmee_0.mp4</baseFile>
                <setImages>
                    <assocData dataType="image" filePath="karlstadt/ChristianGarveAntonGraff.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/EdmundBurke1771.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/Elisabeth_von_Staegemann_Selbstportraet_1808.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/Friedrich_Gentz.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/Jean_Pierre_Frederic_Ancillon_Rinck.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/Kant_gemaelde_1.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/TEI-400.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/kvag_zeidel_diesel_ng_542_2.png"/>
                    <assocData dataType="image" filePath="karlstadt/kvag_zeidel_diesel_nl_202_2.png"/>
                    <assocData dataType="image" filePath="karlstadt/RolleDesFahrkartenautomaten.jpg"/>
                </setImages>
                <imgInterval>10</imgInterval>
            </eventMultimedia>
            <exitStream>
                <nextCity>karlstadt</nextCity>
                <nextStation>1</nextStation>
                <nextPlace>Dh153_arrival</nextPlace>
            </exitStream>
        </event>
    </stream>
</happening>

=== croqueGrec09/KeletiPu/analysyscities/zvw_intervilles.000.xml
<?xml version="1.0" encoding="UTF-8"?>
<happening xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="happening.xsd" idPrefix="iv">
    <stream id="Dh2011" name="Schnellzug Zeidel-Cité d'Orcive-Kvirasim">
        <event id="ZDKV01">
            <eventBody>
                <image lang="all">kvirasim/events/ZDKV01.jpg</image>
                <text lang="de">
                    Du besteigst den Liegewagen nach Kvirasim und schläfst sofort nach Bezug deiner Kabine ein. Es ist 
                    viel mehr passiert, als an so manchen Tagen in deinem studentischen Leben. Die neue Welt, die 
                    eigentlich keine neue Welt ist, sie sieht ja so aus, wie die Erde, aber irgendwie doch ganz anders ...
                    Mit diesem Gefühl wachst du auf, als es in Cité d'Orcive plötzlich heißt: "Alle aussteigen!" Wie gut, 
                    dass du dem Schaffner zugehört hast, als er dir sagte, dass du in den Internight 045 umsteigen musst ...
                    Du schaust dich etwas in der Stadt um, kannst den Bahnhof aber nicht verlassen - denn auch hier befindet 
                    sich eine Analysestadt im Bau.
                </text>
            </eventBody>
            <nextEvent pointRef="ZDKV02"/>
        </event>
        <event id="ZDKV02">
            <eventBody>
                <image lang="all">kvirasim/events/ZDKV02.jpg</image>
                <text lang="de">
                    Nach einer endlos langen Wartezeit besteigst du den Liegewagen im Internight 045 nach Kvirasim. Und 
                    nach mehrtägiger Fahrt kommst du in der Stadt der Phonetik und der Phonologie an. Diese Stadt hat sich 
                    dem Studienkomplex Phonetik + Phonologie gewidmet und die Fächer sind versorgt, die in diesem Studienmodul 
                    angeboten werden. Besteige die Linie U11, um zu sehen, was dich dort erwartet.
                </text>
            </eventBody>
            <exitStream>
                <nextCity>kvirasim</nextCity>
                <nextStation>1</nextStation>
                <nextPlace>hbf_platform6_7a</nextPlace>
            </exitStream>
        </event>
    </stream>
    <stream id="Dh153" name="Schnellzug Darborough-Karlstadt">
        <event id="ZDKA00">
            <eventMultimedia>
                <baseFile>voyage/voyage_Dh153_Bmee_0.mp4</baseFile>
                <setImages>
                    <assocData dataType="image" filePath="karlstadt/ChristianGarveAntonGraff.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/EdmundBurke1771.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/Elisabeth_von_Staegemann_Selbstportraet_1808.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/Friedrich_Gentz.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/Jean_Pierre_Frederic_Ancillon_Rinck.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/Kant_gemaelde_1.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/TEI-400.jpg"/>
                    <assocData dataType="image" filePath="karlstadt/kvag_zeidel_diesel_ng_542_2.png"/>
                    <assocData dataType="image" filePath="karlstadt/kvag_zeidel_diesel_nl_202_2.png"/>
                    <assocData dataType="image" filePath="karlstadt/RolleDesFahrkartenautomaten.jpg"/>
                </setImages>
                <imgInterval>10</imgInterval>
            </eventMultimedia>
            <exitStream>
                <nextCity>karlstadt</nextCity>
                <nextStation>1</nextStation>
                <nextPlace>Dh153_arrival</nextPlace>
            </exitStream>
        </event>
    </stream>
</happening>

=== croqueGrec09/KeletiPu/analysyscities/karlstadt_kvag.xml
<?xml version="1.0" encoding="UTF-8"?>
<happening idPrefix="ka" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="happening.xsd">
    <stream id="bus1101" name="Linie 1101">
        <event id="bus1">
            <eventBody>
                <image lang="all">empty.jpg</image>
                <text>
                    <de>Nun kommst du zur√ºck zum Hauptbahnhof, dem Ausgangspunkt in der Stadt.</de>
                </text>
            </eventBody>
            <exitStream>
                <nextCity>karlstadt</nextCity>
                <nextStation>1</nextStation>
                <nextPlace>ZKBay3_4a</nextPlace>
            </exitStream>
        </event>
    </stream>
</happening>
