=== croqueGrec09/KeletiPu/experiment_box/matrix/matrix.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xs:element name="matrixDB">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="matrix" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="A" type="xs:string"/>
                            <xs:element name="B" type="xs:string"/>
                            <xs:element name="C" type="xs:string"/>
                            <xs:element name="D" type="xs:string"/>
                            <xs:element name="E" type="xs:string"/>
                            <xs:element name="F" type="xs:string"/>
                            <xs:element name="G" type="xs:string"/>
                            <xs:element name="H" type="xs:string"/>
                            <xs:element name="I" type="xs:string"/>
                            <xs:element name="J" type="xs:string"/>
                            <xs:element name="K" type="xs:string"/>
                            <xs:element name="L" type="xs:string"/>
                            <xs:element name="M" type="xs:string"/>
                            <xs:element name="N" type="xs:string"/>
                            <xs:element name="O" type="xs:string"/>
                            <xs:element name="P" type="xs:string"/>
                            <xs:element name="Q" type="xs:string"/>
                            <xs:element name="R" type="xs:string"/>
                            <xs:element name="S" type="xs:string"/>
                            <xs:element name="T" type="xs:string"/>
                            <xs:element name="U" type="xs:string"/>
                            <xs:element name="V" type="xs:string"/>
                            <xs:element name="W" type="xs:string"/>
                            <xs:element name="X" type="xs:string"/>
                            <xs:element name="Y" type="xs:string"/>
                            <xs:element name="Z" type="xs:string"/>
                            <xs:element name="a" type="xs:string"/>
                            <xs:element name="b" type="xs:string"/>
                            <xs:element name="c" type="xs:string"/>
                            <xs:element name="d" type="xs:string"/>
                            <xs:element name="e" type="xs:string"/>
                            <xs:element name="f" type="xs:string"/>
                            <xs:element name="g" type="xs:string"/>
                            <xs:element name="h" type="xs:string"/>
                            <xs:element name="i" type="xs:string"/>
                            <xs:element name="j" type="xs:string"/>
                            <xs:element name="k" type="xs:string"/>
                            <xs:element name="l" type="xs:string"/>
                            <xs:element name="m" type="xs:string"/>
                            <xs:element name="n" type="xs:string"/>
                            <xs:element name="o" type="xs:string"/>
                            <xs:element name="p" type="xs:string"/>
                            <xs:element name="q" type="xs:string"/>
                            <xs:element name="r" type="xs:string"/>
                            <xs:element name="s" type="xs:string"/>
                            <xs:element name="t" type="xs:string"/>
                            <xs:element name="u" type="xs:string"/>
                            <xs:element name="v" type="xs:string"/>
                            <xs:element name="w" type="xs:string"/>
                            <xs:element name="x" type="xs:string"/>
                            <xs:element name="y" type="xs:string"/>
                            <xs:element name="z" type="xs:string"/>
                            <xs:element name="Ä" type="xs:string"/>
                            <xs:element name="ä" type="xs:string"/>
                            <xs:element name="Ö" type="xs:string"/>
                            <xs:element name="ö" type="xs:string"/>
                            <xs:element name="Ü" type="xs:string"/>
                            <xs:element name="ü" type="xs:string"/>
                            <xs:element name="ß" type="xs:string"/>
                            <xs:element name="n0" type="xs:string"/>
                            <xs:element name="n1" type="xs:string"/>
                            <xs:element name="n2" type="xs:string"/>
                            <xs:element name="n3" type="xs:string"/>
                            <xs:element name="n4" type="xs:string"/>
                            <xs:element name="n5" type="xs:string"/>
                            <xs:element name="n6" type="xs:string"/>
                            <xs:element name="n7" type="xs:string"/>
                            <xs:element name="n8" type="xs:string"/>
                            <xs:element name="n9" type="xs:string"/>
                            <xs:element name="n0" type="xs:string"/>
                            <xs:element name="nD" type="xs:string"/>
                            <xs:element name="nE" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="type" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== croqueGrec09/KeletiPu/experiment_box/matrix/matrix.xml
<?xml version="1.0" encoding="UTF-8"?>
<matrixDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="matrix.xsd">
    <matrix type="RSVG">
        <A></A>
        <B></B>
        <C></C>
        <D></D>
        <E></E>
        <F></F>
        <G></G>
        <H></H>
        <I></I>
        <J></J>
        <K></K>
        <L></L>
        <M></M>
        <N></N>
        <O></O>
        <P></P>
        <Q></Q>
        <R>r_rsvg.txt</R>
        <S></S>
        <T></T>
        <U></U>
        <V></V>
        <W></W>
        <X></X>
        <Y></Y>
        <Z></Z>
        <a></a>
        <b></b>
        <c></c>
        <d></d>
        <e></e>
        <f></f>
        <g></g>
        <h></h>
        <i></i>
        <j></j>
        <k></k>
        <l></l>
        <m></m>
        <n></n>
        <o></o>
        <p></p>
        <q></q>
        <r></r>
        <s></s>
        <t></t>
        <u></u>
        <v></v>
        <w></w>
        <x></x>
        <y></y>
        <z></z>
        <Ä></Ä>
        <ä></ä>
        <Ö></Ö>
        <ö></ö>
        <Ü></Ü>
        <ü></ü>
        <ß></ß>
        <n0></n0>
        <n1></n1>
        <n2></n2>
        <n3></n3>
        <n4></n4>
        <n5></n5>
        <n6></n6>
        <n7></n7>
        <n8></n8>
        <n9></n9>
        <n0></n0>
        <nD></nD>
        <nE></nE>
    </matrix>
</matrixDB>
